### ISSUE TITLE
Issue with pelican 4.0.1 

### ISSUE THREAD

**Issue by ryneches** [danielfrg/pelican-ipynb#110]
After upgrading to 4.0.1, I get the following error :

```
ERROR: Could not process ./SuchTree_1.ipynb
  | TypeError: 'bool' object is not callable
  |___
  | Traceback (most recent call last):
  |   File "/home/russell/opt/lib/python3.7/site-packages/pelican/generators.py", line 625, in generate_context
  |     context_sender=self)
  |   File "/home/russell/opt/lib/python3.7/site-packages/pelican/readers.py", line 594, in read_file
  |     content, reader_metadata = reader.read(path)
  |   File "/home/russell/vort.org/plugins/ipynb/markup.py", line 63, in read
  |     _content, metadata = md_reader.read(metadata_filepath)
  |   File "/home/russell/opt/lib/python3.7/site-packages/pelican/readers.py", line 350, in read
  |     self._md = Markdown(**self.settings['MARKDOWN'])
  | TypeError: 'bool' object is not callable
```

**Comment by ryneches** [comment]
Never mind! Turns out the markdown package wasn't installed. I was pretty sure it would install automatically, but evidently not.
