### ISSUE TITLE
AttributeError: 'module' object has no attribute 'register'

### ISSUE THREAD

**Issue by cmertin** [danielfrg/pelican-ipynb#74]
Can not compile. Based on [this issue with org_pandoc_reader](https://github.com/jo-tham/org_pandoc_reader/issues/1), I believe it's a problem with the newer versions of pelican. I get the following error when attempting to compile

    Traceback (most recent call last):                                                                                        
        File "/usr/bin/pelican", line 9, in <module>                                                                              
            load_entry_point('pelican==3.6.3', 'console_scripts', 'pelican')()                                                    
        File "/usr/lib/python2.7/dist-packages/pelican/__init__.py", line 386, in main                                            
            pelican, settings = get_instance(args)                                                                                
        File "/usr/lib/python2.7/dist-packages/pelican/__init__.py", line 380, in get_instance                                    
            return cls(settings), settings                                                                                        
        File "/usr/lib/python2.7/dist-packages/pelican/__init__.py", line 57, in __init__                                         
            self.init_plugins()                                                                                                   
        File "/usr/lib/python2.7/dist-packages/pelican/__init__.py", line 84, in init_plugins                                     
            plugin.register()                                                                                                   
    AttributeError: 'module' object has no attribute 'register'

**Comment by leblancfg** [comment]
Same issue here.

**Comment by brianedelman** [comment]
+1

**Comment by leblancfg** [comment]
Fixed this locally, I was calling the plugin naively with:

~~~python
PLUGIN_PATHS = ['./plugins']
PLUGINS = ['ipynb']
~~~

Should have instead have been done with

~~~python
PLUGIN_PATHS = ['./plugins']
PLUGINS = ['ipynb.markup']
~~~

Clarified README.md to reflect this, see pull request #76 above.

**Comment by danielfrg** [comment]
Fixed on the README now. Thanks!
